name: solution_challenge_project
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.0
  email_validator: ^1.0.6
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  cloud_firestore: "^0.16.0+1"
  google_sign_in: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # Add your assets here
  assets:
    - assets/
    - assets/images/

  ## un-comment this section to add your custom font.
  # fonts:
  #   - family: FONT_NAME
  #     fonts:
  #       - asset: FONT_LOCATION
  #       - asset: FONT_LOCATION
  #         style: italic
  #   - family: ANOTHER_FONT
  #     fonts:
  #       - asset: FONT_LOCATION.ttf
  #       - asset: FONT_LOCATION.ttf
  #         weight: 700